**1. Create a random tensor with shape (7, 7).**




In [1]:
# Import torch
import torch

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.0657, 0.5595, 0.1612, 0.0324, 0.6130, 0.1548, 0.1602],
         [0.0417, 0.0316, 0.3129, 0.1896, 0.2633, 0.4038, 0.4656],
         [0.7012, 0.5832, 0.2721, 0.9015, 0.5206, 0.9777, 0.6875],
         [0.3917, 0.1964, 0.0981, 0.5793, 0.3893, 0.7189, 0.5670],
         [0.4527, 0.8826, 0.1453, 0.1723, 0.2150, 0.8736, 0.4582],
         [0.1535, 0.8445, 0.5846, 0.5895, 0.0188, 0.2220, 0.9822],
         [0.2350, 0.2404, 0.7879, 0.0946, 0.0838, 0.7176, 0.7956]]),
 torch.Size([7, 7]))

**2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).**

In [2]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y) # will error because of shape issues
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape

(tensor([[1.1954],
         [0.8408],
         [2.1616],
         [1.3098],
         [1.8378],
         [1.9423],
         [1.5108]]),
 torch.Size([7, 1]))

**3. Set the random seed to 0 and do 2 & 3 over again.**

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

**4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?**

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

**5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:**

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

**6. Perform a matrix multiplication on the tensors you created in 6**

In [6]:
# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

**7. Find the maximum and minimum values of the output of 7.**

In [7]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min


(tensor(0.5617), tensor(0.3647))

**8. Find the maximum and minimum index values of the output of 7.**

In [8]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min


(tensor(3), tensor(0))

**9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.**

In [9]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
